#!/bin/bash
# Distribution used to test : Fedora 12
# Depend : ImageMagick, unzip

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources" 

## 
TITLE="Diablo II"
PREFIX="DiabloII"
WINEVERSION="1.3.2"
PATCHFILE="D2Patch_113d.exe"
PATCHLINK="http://ftp.blizzard.com/pub/diablo2/patches/PC"
PATCHFILESUM="ce7313b0c35261a2a5f528cd6e2693b5"

POL_SetupWindow_Init
POL_Debug_Init
POL_SetupWindow_presentation "$TITLE" "Blizzard" "www.blizzard.com" "Tinou" "$PREFIX" 

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WINEVERSION"

if [ "$POL_SELECTED_FILE" ]; then
	SetupFile="$POL_SELECTED_FILE"
	POL_SetupWindow_wait "$(eval_gettext 'Installing $TITLE')" "$TITLE"
	POL_Wine start /unix "$SetupFile"
else
	POL_SetupWindow_InstallMethod "CD,LOCAL"
	
	if [ "$INSTALL_METHOD" = "CD" ]; then


		POL_Call POL_Wine_InstallCDROM "INSTALL" "w" "install.exe" "installer.exe"
		POL_Wine_WaitBefore "$TITLE"

		POL_Wine start /unix "$CDROM_SETUP"

		POL_Call POL_Wine_InstallCDROM "PLAYDISC" "w" "d2music.mpq"

		POL_Call POL_Wine_InstallCDROM "CINEMATICS" "w" "playd2.mpq"

		POL_Call POL_Wine_InstallCDROM "INSTALL" "w" "install.exe" "installer.exe"

		POL_Wine_WaitExit "$TITLE"
	
	fi

	if [ "$INSTALL_METHOD" = "LOCAL" ]; then 
		cd "$HOME"
		POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run:')" "$TITLE"
		SetupFile="$APP_ANSWER"
		POL_SetupWindow_wait "$(eval_gettext 'Installing $TITLE')" "$TITLE"
		POL_Wine start /unix "$SetupFile"
	fi
fi

POL_Wine_WaitExit

POL_Shortcut "Diablo II.exe" "$TITLE"
POL_Shortcut_QuietDebug "$TITLE"

POL_SetupWindow_message "$(eval_gettext '$TITLE has been installed successfully.')" "$TITLE"

POL_SetupWindow_Close
exit
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.10 (GNU/Linux)

iEYEABECAAYFAlBB1hcACgkQ5TH6yaoTykeS6ACfWwJDUAO0SdYuV2yjbEsNiOox
PmsAnipw1wZ5uDWNPPDL97qwmz5OfqcC
=UuZA
-----END PGP SIGNATURE-----
