#!/bin/bash
if [ "$PLAYONLINUX" = "" ]; then
    exit 0
fi
source "$PLAYONLINUX/lib/sources"
 
POL_SetupWindow_Init
POL_SetupWindow_presentation "Fallout 2" "Black Isle Studios" "http://fallout.bethsoft.com/" "Matt Caron" "Fallout 2"
 
 
select_prefix "$REPERTOIRE/wineprefix/Fallout2/"
POL_SetupWindow_prefixcreate
cd $HOME
POL_SetupWindow_browse "Plese select the location of the install file" "Select file"

POL_SetupWindow_wait_next_signal "Installing Fallout 2..." "Fallout 2"
wine $APP_ANSWER
 
POL_SetupWindow_detect_exit
 
POL_SetupWindow_reboot
 
 
POL_SetupWindow_make_shortcut "Fallout2" "Program Files/GOG.com/Fallout 2/" "fallout2.exe" "" "Fallout 2"
 
POL_SetupWindow_Close
exit
