#!/bin/bash
if [ "$PLAYONLINUX" = "" ]; then
    exit 0
fi
source "$PLAYONLINUX/lib/sources"
 
POL_SetupWindow_Init
POL_SetupWindow_presentation "Fallout" "Black Isle Studios" "http://fallout.bethsoft.com/" "DemonHypnos" "Fallout"
 
 
select_prefix "$REPERTOIRE/wineprefix/Fallout/"
POL_SetupWindow_prefixcreate
POL_SetupWindow_cdrom
POL_SetupWindow_check_cdrom "setup.exe"
 
Set_OS win98
 
POL_SetupWindow_wait_next_signal "Installing Fallout...make sure to select SMALL INSTALLATION." "Fallout"
wine "$CDROM/setup.exe"
 
POL_SetupWindow_detect_exit
 
POL_SetupWindow_reboot
 
 
POL_SetupWindow_make_shortcut "Fallout" "Program Files/Interplay/Fallout/" "falloutw.exe" "" "Fallout"
 
 
POL_SetupWindow_Close
exit
